pipeline {

    agent any

    environment {
        DOCKER_IMAGE = "nsk7docker/demo-app"
    }

    stages {

        stage('Pre-Clean Workspace') {
           steps {
               dir('SonarJenkins_CICD') {
               cleanWs()
               }
           }
        }

        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/NSKiru-thiga77/CICD_sonarqube_jenkins.git'
            }
        }

        stage('Build') {
            steps {
                dir('SonarJenkins_CICD'){
                sh 'mvn clean package'
                }   
            }
        }

        stage('Test') {
            steps {
                dir('SonarJenkins_CICD'){
                sh 'mvn test'
                }
            }
        }

        stage('Package') {
            steps {
                dir('SonarJenkins_CICD'){
                sh 'mvn compile'
                }
            }
        }
        
        stage('Archive Artifacts') {
            steps {
                dir('SonarJenkins_CICD'){
                archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
                }
            }
        }


        stage('Build Docker Image') {
            steps {
                dir('SonarJenkins_CICD'){
                sh 'docker build -t $DOCKER_IMAGE:tagsonar .'
                }
            }
        }

        stage('Login to DockerHub') {
            steps {
                dir('SonarJenkins_CICD'){
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    sh 'echo $PASS | docker login -u $USER --password-stdin'
                }
                }
            }
        } 

        stage('Push Docker Image') {
            steps {
                dir('SonarJenkins_CICD'){
                sh 'docker push $DOCKER_IMAGE:tagsonar'
                }
            }
        }

        stage('Clean Work Space ') {
            steps {
                dir('SonarJenkins_CICD') {
                    cleanWs()
                }
            }
        }
    }

    post {

        success {
            emailext (
                subject: "SUCCESS: ${env.JOB_NAME}",
                body: "Build ${env.BUILD_NUMBER} succeeded.\n${env.BUILD_URL}",
                to: "kiruthiga.nan@gmail.com"
            )

 
        }

        failure {
            emailext (
                subject: "FAILURE: ${env.JOB_NAME}",
                body: "Build ${env.BUILD_NUMBER} failed.\n${env.BUILD_URL}",
                to: "kiruthiga.nan@gmail.com"
            )


        }
        
    }
}
