pipeline {

    agent any

    environment {
        DOCKER_IMAGE = "nsk7docker/demo-app"
        SONAR_TOKEN = credentials('sonarqube')
        SONAR_HOST_URL = 'http://100.24.19.77/:9000'
    }

    stages {

        stage('Pre-Clean Workspace') {
           steps {
               dir('SonarJenkins_CICD') {
               cleanWs()
               }
           }
        }

        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/NSKiru-thiga77/CICD_sonarqube_jenkins.git'
            }
        }

        stage('Build') {
            steps {
                dir('SonarJenkins_CICD'){
                sh 'mvn clean package'
                }   
            }
        }

        stage('Test') {
            steps {
                dir('SonarJenkins_CICD'){
                sh 'mvn test'
                }
            }
        }

        stage('Package') {
            steps {
                dir('SonarJenkins_CICD'){
                sh 'mvn compile'
                }
            }
        }
        
        stage('Archive Artifacts') {
            steps {
                dir('SonarJenkins_CICD'){
                archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
                }
            }
        }
        
        stage('SonarQube Analysis') {
            steps {
                dir('SonarJenkins_CICD'){
                withSonarQubeEnv('sonarqube_server') {
                    sh '''
                        sonar-scanner \
                        -Dsonar.projectKey=demo-check \
                        -Dsonar.projectName="SonarQube Jenkins CICD" \
                        -Dsonar.projectVersion=1.0 \
                        -Dsonar.sources=src/main/java \
                        -Dsonar.login=$SONAR_TOKEN
                    '''
                    }
                }
            }
        }
        
        stage('Quality Gate') {
            steps {
                dir('SonarJenkins_CICD'){
                timeout(time: 2, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                   }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('SonarJenkins_CICD'){
                sh 'docker build -t $DOCKER_IMAGE:tagsonar .'
                }
            }
        }

        stage('Login to DockerHub') {
            steps {
                dir('SonarJenkins_CICD'){
                withCredentials([usernamePassword(credentialsId: 'dockerhub-cred', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    sh 'echo $PASS | docker login -u $USER --password-stdin'
                }
                }
            }
        } 

        stage('Push Docker Image') {
            steps {
                dir('SonarJenkins_CICD'){
                sh 'docker push $DOCKER_IMAGE:tagsonar'
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('SonarJenkins_CICD')  {
                sh '''
                docker stop demo || true
                docker rm demo || true
                docker run -d -p 8080:8080 --name demo $DOCKER_IMAGE:latest
                '''
                }
            }
        }

        stage('Clean Work Space ') {
            steps {
                dir('SonarJenkins_CICD') {
                    cleanWs()
                }
            }
        }
    }

    post {

        success {
            emailext (
                subject: "SUCCESS: ${env.JOB_NAME}",
                body: "Build ${env.BUILD_NUMBER} succeeded.\n${env.BUILD_URL}",
                to: "kiruthiga.nan@gmail.com"
            )

 
        }

        failure {
            emailext (
                subject: "FAILURE: ${env.JOB_NAME}",
                body: "Build ${env.BUILD_NUMBER} failed.\n${env.BUILD_URL}",
                to: "kiruthiga.nan@gmail.com"
            )


        }
        
    }
}
